### ISSUE TITLE
Add Map to app

### ISSUE THREAD

**Issue by sandradc** [sandradc/bargenp#28]

**Comment by sandradc** [comment]
- **gem added** gem geocoder
- **migration added** changed model Barge : added the keys latitude:float and longitude:float
- **migration added** change_column name of Barge model: from 'postal_code' to 'zip_code'
- **javascript tag added** -- javascript_include_tag "https://maps.googleapis.com/maps/api/js" -- in the layout/application.html.erb file'

**Comment by mbelacat** [comment]
. modif index barges_contoller: added @markers
. added div id map in view barge
. created map.js in javascript/packs 
. added import GMaps from 'gmaps/gmaps.js'
. added <%= javascript_pack_tag "map" %>
. enable google map API and rename it 
. add GOOGLE_API_SERVER_KEY in application.yml
. in config/initializers/geocoder.rb : decomment lookup, add api key, use_https: true
. push this new key to Heroku
. for autocomplete et google maps : enabled Google Maps JavaScript API and Google Places API Web Service
. create GOOGLE_API_BROWSER_KEY
. add GOOGLE_API_BROWSER_KEY in application.yml
. in application.html.erb update javascript_include_tag with GOOGLE_API_BROWSER_KEY
. activate the address autocomplete on the input with the flat_address id in app/javascript/components/autocomplete.js
. Import the function and call it from the map JavaScript pack in app/javascript/packs/map.js
